console.log('--------------------');
console.log('Milenio DataLab - 2016');
console.log('http://milenio.com/datalab');
console.log('');
console.log('Designed by:');
console.log('David Hernández');
console.log('https://twitter.com/MisterEscorpion');
console.log('');
console.log('Developed by:');
console.log('Óscar A. Hernández');
console.log('https://twitter.com/OxcarH');
console.log('--------------------');
